// Vendors the Eltera app stylesheet + brand font into the design-system package
// so the design-sync converter (which bounds cssEntry/extraFonts to the package
// dir) can ship them. Runs on every build, so nothing drifts.
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

// 1) Stylesheet — the design system's source of truth.
copyFileSync(join(here, "..", "src", "styles.css"), join(here, "styles.css"));

// 2) Brand font. The app loads Manrope from Google Fonts at runtime; to ship a
// self-sufficient bundle we vendor the OFL woff2 from Fontsource and re-declare
// @font-face under the family name the CSS uses ("Manrope" — Fontsource names it
// "Manrope Variable"). Only the Latin + Cyrillic subsets are kept (the app is
// RU/EN). Inter, the secondary fallback, is never reached once Manrope loads, so
// it is intentionally not shipped (see .design-sync/config.json runtimeFontPrefixes).
const fontsDir = join(here, "fonts");
rmSync(fontsDir, { recursive: true, force: true });
mkdirSync(fontsDir, { recursive: true });

const KEEP = /(latin|cyrillic)/; // subset filter
const root = join(here, "node_modules", "@fontsource-variable/manrope");
const src = readFileSync(join(root, "index.css"), "utf8");

let faceCss = "/* Eltera brand font — Manrope, vendored from Fontsource (OFL). Generated by vendor-assets.mjs. */\n";
for (const block of src.split(/(?=@font-face)/)) {
  const m = block.match(/url\(\.\/files\/([\w-]+\.woff2)\)/);
  if (!m || !KEEP.test(m[1])) continue;
  faceCss += "\n" + block.split("Manrope Variable").join("Manrope").replace(/url\(\.\/files\//g, "url(./");
  copyFileSync(join(root, "files", m[1]), join(fontsDir, m[1]));
}
writeFileSync(join(fontsDir, "fonts.css"), faceCss);
console.log("vendored styles.css + fonts/ (Manrope latin+cyrillic)");
