"""full schema

Revision ID: b40b5f73abb9
Revises: 
Create Date: 2026-06-09 11:49:49.710890
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40b5f73abb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('tariff', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competencies_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_competencies_organization_id'), ['organization_id'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('patronymic', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_organization_id'), ['organization_id'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('vacancies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.String(length=120), nullable=True),
    sa.Column('selection_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('default_test_id', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancies_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_title'), ['title'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('vacancy_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('selection_type', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('responsible_user_id', sa.String(length=32), nullable=True),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('person_id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_vacancy_id'), ['vacancy_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('head_person_id', sa.String(length=32), nullable=True),
    sa.Column('parent_department_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['head_person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_organization_id'), ['organization_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('competency_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_organization_id'), ['organization_id'], unique=False)

    op.create_table('test_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'version_no')
    )
    with op.batch_alter_table('test_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_versions_test_id'), ['test_id'], unique=False)

    op.create_table('assessment_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('test_version_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('recipient_phone', sa.String(length=40), nullable=True),
    sa.Column('vacancy_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_version_id'], ['test_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_links_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_links_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_links_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_links_token'), ['token'], unique=True)

    op.create_table('employee_profiles',
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=160), nullable=True),
    sa.Column('manager_id', sa.String(length=32), nullable=True),
    sa.Column('project', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=60), nullable=True),
    sa.Column('turnover_risk', sa.String(length=20), nullable=False),
    sa.Column('burnout', sa.String(length=60), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_profiles_department_id'), ['department_id'], unique=False)

    op.create_table('question_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('ai_reference', sa.Text(), nullable=True),
    sa.Column('ai_criteria', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version_no')
    )
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_versions_question_id'), ['question_id'], unique=False)

    op.create_table('test_version_competencies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_version_id', sa.String(length=32), nullable=False),
    sa.Column('competency_id', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_version_id'], ['test_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_version_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_version_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_version_competencies_test_version_id'), ['test_version_id'], unique=False)

    op.create_table('answer_options',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question_version_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_red_flag', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('scale_value', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_options_question_version_id'), ['question_version_id'], unique=False)

    op.create_table('assessment_link_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('link_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['assessment_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_link_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_link_events_link_id'), ['link_id'], unique=False)

    op.create_table('assessment_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('link_id', sa.String(length=32), nullable=True),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('test_version_id', sa.String(length=32), nullable=False),
    sa.Column('respondent_type', sa.String(length=20), nullable=False),
    sa.Column('vacancy_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('red_flags', sa.Integer(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('recommendation_level', sa.String(length=30), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['assessment_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_version_id'], ['test_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_percent'), ['percent'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_respondent_type'), ['respondent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_status'), ['status'], unique=False)

    op.create_table('test_version_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_version_id', sa.String(length=32), nullable=False),
    sa.Column('question_version_id', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_version_id'], ['test_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_version_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_version_items_question_version_id'), ['question_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_version_items_test_version_id'), ['test_version_id'], unique=False)

    op.create_table('session_answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('question_version_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('scale_value', sa.Integer(), nullable=True),
    sa.Column('awarded_score', sa.Integer(), nullable=False),
    sa.Column('is_red_flag', sa.Boolean(), nullable=False),
    sa.Column('ai_status', sa.String(length=20), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_score', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=32), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_answers_session_id'), ['session_id'], unique=False)

    op.create_table('session_competency_scores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('competency_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_competency_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_competency_scores_session_id'), ['session_id'], unique=False)

    op.create_table('ai_scoring_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_answer_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_answer_id'], ['session_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_scoring_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_scoring_jobs_session_answer_id'), ['session_answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_scoring_jobs_status'), ['status'], unique=False)

    op.create_table('session_answer_options',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_answer_id', sa.String(length=32), nullable=False),
    sa.Column('answer_option_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['answer_option_id'], ['answer_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_answer_id'], ['session_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_answer_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_answer_options_session_answer_id'), ['session_answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_answer_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_answer_options_session_answer_id'))

    op.drop_table('session_answer_options')
    with op.batch_alter_table('ai_scoring_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_scoring_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_scoring_jobs_session_answer_id'))

    op.drop_table('ai_scoring_jobs')
    with op.batch_alter_table('session_competency_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_competency_scores_session_id'))

    op.drop_table('session_competency_scores')
    with op.batch_alter_table('session_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_answers_session_id'))

    op.drop_table('session_answers')
    with op.batch_alter_table('test_version_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_version_items_test_version_id'))
        batch_op.drop_index(batch_op.f('ix_test_version_items_question_version_id'))

    op.drop_table('test_version_items')
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_respondent_type'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_person_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_percent'))
        batch_op.drop_index(batch_op.f('ix_assessment_sessions_organization_id'))

    op.drop_table('assessment_sessions')
    with op.batch_alter_table('assessment_link_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_link_events_link_id'))

    op.drop_table('assessment_link_events')
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_options_question_version_id'))

    op.drop_table('answer_options')
    with op.batch_alter_table('test_version_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_version_competencies_test_version_id'))
        batch_op.drop_index(batch_op.f('ix_test_version_competencies_competency_id'))

    op.drop_table('test_version_competencies')
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_versions_question_id'))

    op.drop_table('question_versions')
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_profiles_department_id'))

    op.drop_table('employee_profiles')
    with op.batch_alter_table('assessment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_links_token'))
        batch_op.drop_index(batch_op.f('ix_assessment_links_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_links_person_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_links_organization_id'))

    op.drop_table('assessment_links')
    with op.batch_alter_table('test_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_versions_test_id'))

    op.drop_table('test_versions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_questions_competency_id'))

    op.drop_table('questions')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_organization_id'))

    op.drop_table('departments')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_stage'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_source'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_title'))
        batch_op.drop_index(batch_op.f('ix_vacancies_organization_id'))

    op.drop_table('vacancies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tests_key'))

    op.drop_table('tests')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_organization_id'))
        batch_op.drop_index(batch_op.f('ix_people_full_name'))
        batch_op.drop_index(batch_op.f('ix_people_email'))
        batch_op.drop_index(batch_op.f('ix_people_city'))

    op.drop_table('people')
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competencies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_competencies_key'))

    op.drop_table('competencies')
    op.drop_table('organizations')
    # ### end Alembic commands ###
