"""employee fit

Revision ID: 5ac3829d1db4
Revises: c4b492613cc8
Create Date: 2026-06-10 11:01:05.168804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac3829d1db4'
down_revision: Union[str, None] = 'c4b492613cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_column('fit')

    # ### end Alembic commands ###
