"""session answers_snapshot

Revision ID: c4b492613cc8
Revises: 30a048612c16
Create Date: 2026-06-09 18:01:56.492033
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b492613cc8'
down_revision: Union[str, None] = '30a048612c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_column('answers_snapshot')

    # ### end Alembic commands ###
