"""session report_narrative

Revision ID: 30a048612c16
Revises: b40b5f73abb9
Create Date: 2026-06-09 17:39:27.881243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a048612c16'
down_revision: Union[str, None] = 'b40b5f73abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_narrative', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_column('report_narrative')

    # ### end Alembic commands ###
